language: go
notificaitons:
  email:
    recipients: jason.mcvetta@gmail.com
    on_success: change
    on_failure: always
before_script:
- go get -v github.com/jmcvetta/randutil
- go get -v github.com/darkhelmet/env
- go get -v github.com/bmizerany/assert
env:
  global:
  - secure: L4wajfckE2Rfz6yqLckSqoGns4U5zDN2V1RRS9JLQT63OtNoJVDJSFPkN7nJUVEmoOLWZ2NlTovRsrU+WlmgR/xIIqMA4OJRtL8+jNLvgqE0cCEWOfREkkv0DVQSvbc0OIkKr1ImpagtftP0XbNmfzWEKHbzNM/ggLthz04Bu1Q=
  - secure: jr7ZTKeox17n6uQk2uRJTlkaK6mm3yNA1jwZqUZGxX6u90loUxF2BpECfbYLtbR5DKcnWJUL9onX2LiTxVkk5sWZLCLm7GVS5eVzNrXMEW10aCVglISHKHEfaVW5eXiyf2juFu6KES+2j2DshctuVfqKJeWZR2bONIQDXmnkuAo=
  - secure: Lug+mREVv3Xh+iyIUdfHAWsJtJEsd8cLjnlUeNEavuTMxAw2H7fZ7hBPDsYtLzLby+s86NHiIrKVhGjBLm+A2QdM2HPrNj+F9lzcZ62amJ6ZbIuZMfnj2uOlVWbV4yI4V3MM/J8tukwpvhAP7YEXbMdWkhVAAdsG+jyUjBGihLc=
